#!/usr/bin/env python3
"""Merge generated service OpenAPI documents into the active public API."""

from __future__ import annotations

import copy
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[1]
DOCUMENTS = (
    ROOT / "openapi/identity/v1/identity.openapi.yaml",
    ROOT / "openapi/member/v1/member.openapi.yaml",
    ROOT / "openapi/plans/v1/plans.openapi.yaml",
    ROOT / "openapi/checkin/v1/checkin.openapi.yaml",
    ROOT / "openapi/trainer/v1/trainer.openapi.yaml",
)
OUTPUT = ROOT / "openapi/gym-active-api.openapi.yaml"
HTTP_METHODS = {"get", "post", "put", "patch", "delete", "head", "options", "trace"}


def merge_value(target: dict, name: str, value: object, source: Path) -> None:
    current = target.get(name)
    if current is None:
        target[name] = copy.deepcopy(value)
    elif current != value:
        raise SystemExit(f"conflicting {name} from {source}")


def merge_document(merged: dict, document: dict, source: Path) -> None:
    for name in ("openapi", "info", "security"):
        if name in document:
            merge_value(merged, name, document[name], source)

    merged_paths = merged.setdefault("paths", {})
    for path, path_item in document.get("paths", {}).items():
        target_path_item = merged_paths.setdefault(path, {})
        for method, operation in path_item.items():
            if method.lower() in HTTP_METHODS and method in target_path_item:
                raise SystemExit(f"duplicate operation {method.upper()} {path} from {source}")
            merge_value(target_path_item, method, operation, source)

    merged_components = merged.setdefault("components", {})
    for group, entries in document.get("components", {}).items():
        target_entries = merged_components.setdefault(group, {})
        for name, value in entries.items():
            merge_value(target_entries, name, value, source)

    tags = merged.setdefault("tags", [])
    for tag in document.get("tags", []):
        if tag not in tags:
            tags.append(copy.deepcopy(tag))


def render() -> str:
    merged: dict = {}
    for source in DOCUMENTS:
        merge_document(merged, yaml.safe_load(source.read_text()), source)
    return "# Generated by scripts/merge-openapi.py. Do not edit.\n" + yaml.safe_dump(
        merged,
        allow_unicode=True,
        sort_keys=True,
    )


def given_service_openapi_when_merged_then_write_deterministic_active_document() -> None:
    first = render()
    second = render()
    if first != second:
        raise SystemExit("active OpenAPI merge is not deterministic")
    OUTPUT.write_text(first)


if __name__ == "__main__":
    given_service_openapi_when_merged_then_write_deterministic_active_document()
